version: "3.8"

services:
  colors-management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5007
      - ConnectionStrings__DefaultConnection=Server=db;Database=colors_db;User Id=sa;Password=YourNewStr0ng@Passw0rd;Encrypt=False;TrustServerCertificate=True
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourNewStr0ng@Passw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      test:
        [
          "CMD",
          "sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "YourNewStr0ng@Passw0rd",
          "-Q",
          "SELECT 1",
        ]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 3s
